In [2]:
import numpy as np 

asList = [1, 2, 3]
asArray = np.array([1, 2, 3]) # 1 dimension
rowVec = np.array([[1, 2, 3]]) # row
colVec = np.array([[1],
                 [2],
                 [3]]) # col

In [3]:
print(f'asList : {np.shape(asList)}')
print(f'asArray: {asArray.shape}')
print(f'rowVec : {rowVec.shape}')
print(f'colVec : {colVec.shape}')

asList : (3,)
asArray: (3,)
rowVec : (1, 3)
colVec : (3, 1)


In [7]:
v = np.array([4, 5, 6])
w = np.array([10, 20, 30])
u = np.array([0, 3, 6, 9])
nPlusW = v + w
# uPlusM = u + w # error, 벡터의 차원이 다름


nPlusW

array([14, 25, 36])

In [10]:
# Broadcasting _ python

v = np.array([[4, 5, 6]])
w = np.array([[10, 20, 30]]).T # Transpose
v + w


array([[14, 15, 16],
       [24, 25, 26],
       [34, 35, 36]])

In [14]:
# Scalar - Vector multiplication

s = 2#.0
a = [3, 4, 5]
b = np.array(a)
print(a*s)
print(b*s)

[3, 4, 5, 3, 4, 5]
[ 6  8 10]


In [25]:
s = 2
v = np.array([3, 6])
s+v

array([5, 8])

In [26]:
v = np.array([[1, 2, 3]]).T
w = np.array([[10, 20]])
v+w

array([[11, 21],
       [12, 22],
       [13, 23]])

In [27]:
v = np.array([1, 2, 3, 7, 8, 9])
v_dim = len(v)
v_mag = np.linalg.norm(v)
print(v_dim, v_mag)

6 14.422205101855956


In [16]:
# dot product
v = np.array([1, 2, 3, 4])
w = np.array([5, 6, 7, 8])
np.dot(v,w) # 5 + 12 + 21 + 32

70

In [17]:
s = 10
np.dot(s*v, w)

700

In [19]:
a = np.array([0, 1, 2])
b = np.array([3, 5, 8])
c = np.array([13, 21, 34])

res1 = np.dot(a, b+c)
res2 = np.dot(a, b) + np.dot(a, c)
print(res1, res2)

110 110


In [21]:
# Hardamard product
a = np.array([5, 4, 8, 2])
b = np.array([1, 0, .5, -1])
a*b

array([ 5.,  0.,  4., -2.])

In [34]:
# 직교벡터 분해 (p. 45)
# orthogonal projection 직교 투영법

a = np.array([6, 8])
b = np.array([3, 1])
beta = np.dot(a.T, b) / np.dot(a.T, a)
beta

0.26

In [31]:
# 피타고라스
(np.linalg.norm(b)**2 - (beta*np.linalg.norm(a))**2)**0.5

1.8000000000000003

In [33]:
# b - beta*a
tmpVec = b - beta*a
np.linalg.norm(tmpVec)

1.8

In [35]:
# p. 50 https://github.com/Sancho-kim/LinAlg4DS

In [39]:
# 1-1

w = np.array([10, 20, 30, 40])
u = np.array([0, 3, 6, 9])

u + w

array([10, 23, 36, 49])

In [42]:
# 1-2
# p-norm

def pNorm(X : np.array, p : int):
    sum = 0
    for x in X:
        sum += x**p
    return sum**(1/p)


import numpy as np

# 1. 임의의 난수 벡터 생성 (크기 3의 벡터)
np.random.seed(42)

random_vector = np.random.randn(3)
print("Random vector:", random_vector)

# 2. 단위 벡터(방향만 유지) 구하기
magnitude = np.linalg.norm(random_vector)  # 벡터의 크기 계산
unit_vector = random_vector / magnitude    # 단위 벡터로 변환
print("Unit vector:", unit_vector)

# 3. 난수로 크기 조정 (0에서 10 사이의 난수 크기)
random_magnitude = np.random.uniform(0, 10)
new_vector = unit_vector * random_magnitude  # 단위 벡터에 크기를 곱함
print("New vector with random magnitude:", new_vector)

print(new_vector, np.linalg.norm(new_vector), pNorm(new_vector, 2))


Random vector: [ 0.49671415 -0.1382643   0.64768854]
Unit vector: [ 0.60000205 -0.1670153   0.78237039]
New vector with random magnitude: [ 0.93611503 -0.260575    1.22064365]
[ 0.93611503 -0.260575    1.22064365] 1.560186404424365 1.560186404424365


In [43]:
# 1-3

def return_unit_vector(vec : np.array):
    return vec / np.linalg.norm(vec)

return_unit_vector(new_vector)

array([ 0.60000205, -0.1670153 ,  0.78237039])

In [57]:
# 1-4

def parallel_vector(vec : np.array):
    return return_unit_vector(vec) * np.random.randint(0, 100)

parallel_vector(new_vector)

array([ 44.40015139, -12.35913224,  57.8954092 ])

In [71]:
# 1-5 ...

def mTranspose(vec : np.array):
    row, col = 0, 0
    try:
        row = vec.shape[1]
    except IndexError as e:
        return np.array()

    try:
        col = vec.shape[0]
    except IndexError as e:
        pass

    rtn = np.zeros((row, col))
    
    for i in range(row):
        for j in range(col):
            rtn[i, j] = vec[j, i]

    return rtn

mTranspose(new_vector)

array([], shape=(0, 3), dtype=float64)

In [72]:
vec = new_vector
row, col = 0, 0
try:
    row = vec.shape[1]
except IndexError as e:
    pass

try:
    col = vec.shape[0]
except IndexError as e:
    pass

vec[1, 0]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed